# Generated by Django 2.1.7 on 2019-03-23 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_auto_20190323_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminreply',
            old_name='issue_description',
            new_name='admin_reply',
        ),
        migrations.RenameField(
            model_name='userreply',
            old_name='issue_description',
            new_name='user_reply',
        ),
    ]
