# Generated by Django 2.1.5 on 2019-03-18 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_auto_20190318_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='resolved',
            field=models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], max_length=3),
        ),
    ]
