# Generated by Django 2.1.5 on 2019-03-18 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_adminreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminreply',
            name='message_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.Message'),
        ),
    ]
