# Generated by Django 2.1.5 on 2019-03-18 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_userreply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreply',
            name='message_link',
        ),
        migrations.RemoveField(
            model_name='userreply',
            name='user',
        ),
        migrations.AddField(
            model_name='message',
            name='admin_reply_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.AdminReply'),
        ),
        migrations.DeleteModel(
            name='UserReply',
        ),
    ]
