# Generated by Django 2.1.5 on 2019-03-18 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0013_auto_20190318_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreply',
            name='resolved',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.Message'),
        ),
    ]
