# Generated by Django 2.1.5 on 2019-03-18 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0014_userreply_resolved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userreply',
            old_name='message_link',
            new_name='admin_reply_link',
        ),
    ]
