# Generated by Django 2.1.5 on 2019-04-05 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0015_auto_20190318_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReactMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('group', models.CharField(max_length=50)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
