# Generated by Django 2.1.5 on 2019-04-05 02:17

from django.db import migrations, models
import mysite.validators


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0016_reactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='reactmessage',
            name='content',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='reactmessage',
            name='document',
            field=models.FileField(null=True, upload_to='testfolder', validators=[mysite.validators.validate_extension]),
        ),
        migrations.AddField(
            model_name='reactmessage',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reactmessage',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reactmessage',
            name='submit_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
