# Generated by Django 2.1.5 on 2019-04-05 02:56

from django.db import migrations, models
import mysite.validators


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0017_auto_20190405_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactmessage',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='testfolder', validators=[mysite.validators.validate_extension]),
        ),
    ]
