# Generated by Django 2.1.5 on 2019-04-05 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0018_auto_20190405_0256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reactmessage',
            name='document',
        ),
    ]
